const data = [
    {
        id: 1,
        name: "Sunny Beach Resort",
        image_url: "https://example.com/images/sunny-beach-resort.jpg",
        cost: 200,
        state: "California",
        city: "Malibu",
    },
    {
        id: 2,
        name: "Mountain View Lodge",
        image_url: "https://example.com/images/mountain-view-lodge.jpg",
        cost: 150,
        state: "Colorado",
        city: "Aspen",
    },
    {
        id: 3,
        name: "Oceanfront Paradise",
        image_url: "https://example.com/images/oceanfront-paradise.jpg",
        cost: 350,
        state: "Hawaii",
        city: "Honolulu",
    },
    {
        id: 4,
        name: "City Lights Hotel",
        image_url: "https://example.com/images/city-lights-hotel.jpg",
        cost: 120,
        state: "New York",
        city: "New York",
    },
    {
        id: 5,
        name: "Desert Oasis Resort",
        image_url: "https://example.com/images/desert-oasis-resort.jpg",
        cost: 180,
        state: "Arizona",
        city: "Sedona",
    },
    {
        id: 6,
        name: "Riverside Retreat",
        image_url: "https://example.com/images/riverside-retreat.jpg",
        cost: 220,
        state: "Oregon",
        city: "Bend",
    },
    {
        id: 7,
        name: "Forest Escape",
        image_url: "https://example.com/images/forest-escape.jpg",
        cost: 140,
        state: "Oregon",
        city: "Portland",
    },
    {
        id: 8,
        name: "Grand Canyon Lodge",
        image_url: "https://example.com/images/grand-canyon-lodge.jpg",
        cost: 250,
        state: "Arizona",
        city: "Grand Canyon",
    },
    {
        id: 9,
        name: "Skyline Towers",
        image_url: "https://example.com/images/skyline-towers.jpg",
        cost: 300,
        state: "Illinois",
        city: "Chicago",
    },
    {
        id: 10,
        name: "Palm Springs Inn",
        image_url: "https://example.com/images/palm-springs-inn.jpg",
        cost: 210,
        state: "California",
        city: "Palm Springs",
    },
    {
        id: 11,
        name: "Cedar Valley Resort",
        image_url: "https://example.com/images/cedar-valley-resort.jpg",
        cost: 190,
        state: "Idaho",
        city: "Boise",
    },
    {
        id: 12,
        name: "Starlight Hotel",
        image_url: "https://example.com/images/starlight-hotel.jpg",
        cost: 170,
        state: "Nevada",
        city: "Las Vegas",
    },
    {
        id: 13,
        name: "Sunset Bay Inn",
        image_url: "https://example.com/images/sunset-bay-inn.jpg",
        cost: 210,
        state: "Florida",
        city: "Key West",
    },
    {
        id: 14,
        name: "The Alpine Lodge",
        image_url: "https://example.com/images/alpine-lodge.jpg",
        cost: 160,
        state: "Colorado",
        city: "Aspen",
    },
    {
        id: 15,
        name: "Tropical Breeze Resort",
        image_url: "https://example.com/images/tropical-breeze-resort.jpg",
        cost: 230,
        state: "Florida",
        city: "Miami",
    },
    {
        id: 16,
        name: "Silver Mountain Hotel",
        image_url: "https://example.com/images/silver-mountain-hotel.jpg",
        cost: 280,
        state: "California",
        city: "Lake Tahoe",
    },
    {
        id: 17,
        name: "Harbor View Resort",
        image_url: "https://example.com/images/harbor-view-resort.jpg",
        cost: 220,
        state: "Washington",
        city: "Seattle",
    },
    {
        id: 18,
        name: "Redwood Retreat",
        image_url: "https://example.com/images/redwood-retreat.jpg",
        cost: 240,
        state: "California",
        city: "Mendocino",
    },
    {
        id: 19,
        name: "Golden Gate Hotel",
        image_url: "https://example.com/images/golden-gate-hotel.jpg",
        cost: 350,
        state: "California",
        city: "San Francisco",
    },
    {
        id: 20,
        name: "Blue Ridge Inn",
        image_url: "https://example.com/images/blue-ridge-inn.jpg",
        cost: 180,
        state: "Georgia",
        city: "Blue Ridge",
    },
    {
        id: 21,
        name: "Crystal Waters Resort",
        image_url: "https://example.com/images/crystal-waters-resort.jpg",
        cost: 190,
        state: "Florida",
        city: "Clearwater",
    },
    {
        id: 22,
        name: "Oasis by the Sea",
        image_url: "https://example.com/images/oasis-by-the-sea.jpg",
        cost: 210,
        state: "California",
        city: "San Diego",
    },
    {
        id: 23,
        name: "The Mountain Peak Inn",
        image_url: "https://example.com/images/mountain-peak-inn.jpg",
        cost: 260,
        state: "Colorado",
        city: "Breckenridge",
    },
    {
        id: 24,
        name: "Luxury Lakeside Hotel",
        image_url: "https://example.com/images/luxury-lakeside-hotel.jpg",
        cost: 320,
        state: "New York",
        city: "Lake Placid",
    },
    {
        id: 25,
        name: "Windy Ridge Hotel",
        image_url: "https://example.com/images/windy-ridge-hotel.jpg",
        cost: 280,
        state: "Massachusetts",
        city: "Cape Cod",
    },
    {
        id: 26,
        name: "Coastal Haven Inn",
        image_url: "https://example.com/images/coastal-haven-inn.jpg",
        cost: 250,
        state: "California",
        city: "Monterey",
    },
    {
        id: 27,
        name: "Sunrise Bay Hotel",
        image_url: "https://example.com/images/sunrise-bay-hotel.jpg",
        cost: 230,
        state: "South Carolina",
        city: "Charleston",
    },
    {
        id: 28,
        name: "The Grand Resort",
        image_url: "https://example.com/images/grand-resort.jpg",
        cost: 350,
        state: "California",
        city: "Napa Valley",
    },
    {
        id: 29,
        name: "Desert Bloom Hotel",
        image_url: "https://example.com/images/desert-bloom-hotel.jpg",
        cost: 160,
        state: "Arizona",
        city: "Phoenix",
    },
    {
        id: 30,
        name: "Cozy Cove Lodge",
        image_url: "https://example.com/images/cozy-cove-lodge.jpg",
        cost: 150,
        state: "Maine",
        city: "Portland",
    },
    {
        id: 31,
        name: "The Seaside Retreat",
        image_url: "https://example.com/images/seaside-retreat.jpg",
        cost: 270,
        state: "California",
        city: "Santa Cruz",
    },
    {
        id: 32,
        name: "Crystal Sands Resort",
        image_url: "https://example.com/images/crystal-sands-resort.jpg",
        cost: 290,
        state: "Florida",
        city: "Miami Beach",
    },
    {
        id: 33,
        name: "Cascadia Hotel",
        image_url: "https://example.com/images/cascadia-hotel.jpg",
        cost: 320,
        state: "Oregon",
        city: "Portland",
    },
    {
        id: 34,
        name: "Whispering Pines Resort",
        image_url: "https://example.com/images/whispering-pines-resort.jpg",
        cost: 240,
        state: "California",
        city: "Lake Tahoe",
    },
    {
        id: 35,
        name: "Starlight Ridge Inn",
        image_url: "https://example.com/images/starlight-ridge-inn.jpg",
        cost: 180,
        state: "Arizona",
        city: "Sedona",
    },
    {
        id: 36,
        name: "Moonlit Beach Resort",
        image_url: "https://example.com/images/moonlit-beach-resort.jpg",
        cost: 300,
        state: "Hawaii",
        city: "Maui",
    },
    {
        id: 37,
        name: "The Bayview Hotel",
        image_url: "https://example.com/images/bayview-hotel.jpg",
        cost: 210,
        state: "California",
        city: "San Francisco",
    },
    {
        id: 38,
        name: "Sunset Mountain Lodge",
        image_url: "https://example.com/images/sunset-mountain-lodge.jpg",
        cost: 220,
        state: "Montana",
        city: "Bozeman",
    },
    {
        id: 39,
        name: "The Horizon Inn",
        image_url: "https://example.com/images/horizon-inn.jpg",
        cost: 260,
        state: "Michigan",
        city: "Grand Haven",
    },
    {
        id: 40,
        name: "Laguna Cliffside Hotel",
        image_url: "https://example.com/images/laguna-cliffside-hotel.jpg",
        cost: 320,
        state: "California",
        city: "Laguna Beach",
    },
];

const searchInput = document.querySelector("#search input");
const searchButton = document.querySelector("#search button");
const getResult = (val) => {
    const result = data.filter((item) => {
        return (
            item.city.toLowerCase() == val.toLowerCase() ||
            item.state.toLowerCase() == val.toLowerCase()
        );
    });
    console.log(result);
    return result;
};
searchButton.onclick = function () {
    getResult(searchInput.value);
};
